version: '3.1'

name: mongo4weather-dev

services:
  mongo:
    image: mongo:5.0.26-rc0-focal
    restart: always
    container_name: mweather_dev
    ports:
      - 9071:27017
    volumes:
      - .\databaseData:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: weather
      MONGO_INITDB_ROOT_PASSWORD: weatherpwd
    networks:
      - mongo_network

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    restart: always
    container_name: mongo_ui_dev
    ports:
      - 9072:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: weather
      ME_CONFIG_MONGODB_ADMINPASSWORD: weatherpwd
      ME_CONFIG_BASICAUTH_USERNAME: weather
      ME_CONFIG_BASICAUTH_PASSWORD: weatherpwd
      ME_CONFIG_MONGODB_URL: mongodb://weather:weatherpwd@mongo:27017/
    depends_on:
      - mongo
    networks:
      - mongo_network

networks:
  mongo_network: {}
