version: '3.1'

name: weather-prod

services:
  mongo:
    image: mongo:7.0.6-jammy
    restart: always
    container_name: mweather
    ports:
      - 9076:27017
    volumes:
      - .\databaseData:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: weather
      MONGO_INITDB_ROOT_PASSWORD: weatherpwd
    networks:
      - weather-network

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    restart: always
    container_name: mongo_ui
    ports:
      - 9077:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: weather
      ME_CONFIG_MONGODB_ADMINPASSWORD: weatherpwd
      ME_CONFIG_BASICAUTH_USERNAME: weather
      ME_CONFIG_BASICAUTH_PASSWORD: weatherpwd
      ME_CONFIG_MONGODB_URL: mongodb://weather:weatherpwd@mongo:27017/
    depends_on:
      - mongo
    networks:
      - weather-network

  weather-station:
    image: qjetuska/weather-station:0.0.1
    container_name: weather-station-ms
    ports: 
      - 9075:9075
    networks:
      - weather-network
    environment:
      SPRING_PROFILES_ACTIVE: prod
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_USERNAME: weather
      MONGO_PASSWORD: weatherpwd
    depends_on:
      - mongo
  
  weather-station-simulator:
    image: qjetuska/weather-station-simulator:0.0.1
    container_name: weather-station-simulator-ms
    networks:
      - weather-network
    environment:
      WEATHER_SERVER: weather-station
      WEATHER_PORT: 9075
    depends_on:
      - weather-station

networks:
  weather-network: {}
